### ISSUE TITLE
rust-analyzer not found and not downloading 

### ISSUE THREAD

**Issue by s1341** [fannheyward/coc-rust-analyzer#704]
Every time I open neovim or reload rust-analyzer, I get the Rust analyzer is not found error.

I am on nixos. It used to work, I believe an update broke it. I'm using coc-rust-analyzer 0.43.0.

**Comment by fannheyward** [comment]
I've published v0.43.1, please `:CocUpdate` and try again.

**Comment by s1341** [comment]
Ok. Looks to be fixed... Although `:ALEInfo` still shows `(executable check - failure) rust-analyzer`

**Comment by fannheyward** [comment]
That's ale's issue.

**Comment by s1341** [comment]
This bug is back! 

I closed and reopened neovim and the issue is recurring.

**Comment by s1341** [comment]
Any Idea how to work around or fix this issue? Can I provide more info?

**Comment by fannheyward** [comment]
Have no idea about it, I don't have a nix env. After rust-analyzer is downloaded, coc-rust-analyzer will patch it with `nix-build`,  https://github.com/fannheyward/coc-rust-analyzer/blob/master/src/downloader.ts#L16, same as VSCode https://github.com/rust-analyzer/rust-analyzer/blob/master/editors/code/src/main.ts#L245.

Maybe you can install rust-analyzer manually, and set `rust-analyzer.server.path` in coc-settings.json.

**Comment by s1341** [comment]
Ok. Thanks.
